vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        images_upload:
            uri_prefix: /images/sells
            upload_destination: '%kernel.project_dir%/public/images/sells'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
