-- MySQL Script generated by MySQL Workbench
-- Fri Oct 21 16:05:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT GENERATED ALWAYS AS (),
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(50) NOT NULL,
  `mobile` VARCHAR(15) NULL,
  `is_admin` VARCHAR(20) GENERATED ALWAYS AS (false),
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_UNIQUE` (`id_user` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mydb`.`card_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`card_user` (
  `id_card` INT GENERATED ALWAYS AS (),
  `fk_id_user` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `quality` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_card`),
  INDEX `fk_card_user1_idx` (`fk_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_card_user1`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`command`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`command` (
  `id_command` INT GENERATED ALWAYS AS (),
  `id_user` INT NOT NULL,
  `shipping` FLOAT NULL,
  `total` FLOAT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `status_command` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_command`),
  INDEX `fk_command_user1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_command_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_info` (
  `id_user_info` INT NOT NULL,
  `fk_id_user` INT NOT NULL,
  `city` VARCHAR(50) NULL,
  `country` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `delivery_address` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user_info`, `fk_id_user`),
  INDEX `fk_user_info_user1_idx` (`fk_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_info_user1`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cata_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cata_card` (
  `id_cata_card` INT GENERATED ALWAYS AS (),
  `fk_id_card` INT NOT NULL,
  `api_card_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `cara_card_link` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cata_card`),
  INDEX `fk_cata_card_card1_idx` (`fk_id_card` ASC) VISIBLE,
  CONSTRAINT `fk_cata_card_card1`
    FOREIGN KEY (`fk_id_card`)
    REFERENCES `mydb`.`card_user` (`id_card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`card_set`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`card_set` (
  `id_card_set` INT NOT NULL,
  `fk_id_card` INT NOT NULL,
  `fk_id_cata_card` INT NOT NULL,
  `api_set_id` VARCHAR(45) NOT NULL,
  `set_name` VARCHAR(45) NOT NULL,
  `set_link` VARCHAR(45) NOT NULL,
  `set_img` VARCHAR(45) NULL,
  PRIMARY KEY (`id_card_set`),
  INDEX `fk_card_category_card1_idx` (`fk_id_card` ASC) VISIBLE,
  INDEX `fk_card_set_cata_card1_idx` (`fk_id_cata_card` ASC) VISIBLE,
  CONSTRAINT `fk_card_category_card1`
    FOREIGN KEY (`fk_id_card`)
    REFERENCES `mydb`.`card_user` (`id_card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_card_set_cata_card1`
    FOREIGN KEY (`fk_id_cata_card`)
    REFERENCES `mydb`.`cata_card` (`id_cata_card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_item` (
  `id_order_item` INT NOT NULL,
  `fk_id_command` INT NOT NULL,
  `fk_id_card` INT NOT NULL,
  `quantity` FLOAT NOT NULL,
  `discount` FLOAT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id_order_item`),
  INDEX `fk_order_item_command1_idx` (`fk_id_command` ASC) VISIBLE,
  INDEX `fk_order_item_card1_idx` (`fk_id_card` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_command1`
    FOREIGN KEY (`fk_id_command`)
    REFERENCES `mydb`.`command` (`id_command`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_card1`
    FOREIGN KEY (`fk_id_card`)
    REFERENCES `mydb`.`card_user` (`id_card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games` (
  `id_games` INT GENERATED ALWAYS AS (),
  `names` ENUM('pokemon') NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id_games`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`card_serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`card_serie` (
  `id_card_serie` INT NOT NULL,
  `fk_id_card_set` INT NOT NULL,
  `fk_id_games` INT NOT NULL,
  `serie_name` VARCHAR(45) NOT NULL,
  `serie_link` VARCHAR(45) NULL,
  `serie_img` VARCHAR(45) NULL,
  PRIMARY KEY (`id_card_serie`),
  INDEX `fk_card_serie_card_set1_idx` (`fk_id_card_set` ASC) VISIBLE,
  INDEX `fk_card_serie_games1_idx` (`fk_id_games` ASC) VISIBLE,
  CONSTRAINT `fk_card_serie_card_set1`
    FOREIGN KEY (`fk_id_card_set`)
    REFERENCES `mydb`.`card_set` (`id_card_set`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_card_serie_games1`
    FOREIGN KEY (`fk_id_games`)
    REFERENCES `mydb`.`games` (`id_games`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
