version: '3.8'

services:

  database:
    image: mysql
    container_name: db_tcg_market
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: TcgMarket
      MYSQL_USER: tcg_user
      MYSQL_PASSWORD: tcg_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #Permet de conserver les données de la base à la fermeture du docker
      - ./data/:/var/lib/mysql
    ports:
      - "13306:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_tcg_marke
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      #On défini le host mySql
      PMA_HOST: database

  web:
    build: docker
    container_name: web_tcg_market
    ports:
      - "8000:80"
    volumes:
      #passe la config des vh dans le container
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always

